### ISSUE TITLE
Why move files to the root?

### ISSUE THREAD

**Issue by bebaps** [factor1/prelude-wp#68]
Let's open up a discussion on why this happens, I am failing to see the benefit.

Comparing the source files in the repo to what you end up with after the move, why not just have all of the files in the root to begin with? That way the `package.json` does not get deleted and we wont need to run `npm init`. Also, I think that is would make the project easier to install from the jump for a wider range of people. As it stands, Prelude must be installed via `npm install ...` in order for it to be set up properly. Why is that? We cannot assume that anyone will actually read the instructions for getting started, as simple as they may be... but anyone that tries to install Prelude via cloning the repo directly, or using a package manager via `npm install https://github.com/factor1/prelude-wp.git` or `bower install https://github.com/factor1/prelude-wp.git` will get errors that I think can easily be avoided.

We also know that currently there are issues when installed on systems that are not Mac OSX. Although so far this is an isolated issue, the fact that we have almost no testing on Windows machines I think is more reason to just have the files in the project root from the beginning.

Open to discussion.

**Comment by erwstout** [comment]
I think you may be looking at it a little bit wrong. Prelude moves files on install as a connivence so that the user doesn't have to copy the needed files themselves. NPM packages should be self contained and have their own `package.json` files. The reason we move the files into the user's project directory is because a user should be setting up their project with `npm init` and its own `package.json` so that they can add/edit their own dependencies. Cloning the repo and then adding your own dependencies to Prelude's `package.json` is inherently wrong. That would be like cloning `gulp-sass` and then building your project off of their json file. 

So when it comes down to it, for a wordpress theme you should have its own project json file, with a list of dependencies. Such as:

"New WordPress Theme Package!"
- Prelude
- Slick Slider
- Nifty Nav
- Font Awesome

And then each one of those dependencies have their own dependencies that get installed from their `package.json` files.

As far as other operating systems go, it works correctly on all operating systems. Windows is not officially supported yet because windows doesnt actually officially support `npm` without heavy modifications/tools to get command line working. The only thing that fails on Linux currently is the image compression package, which is out of our control at the moment, but the entire prelude package works as expected apart from that.

**Comment by erwstout** [comment]
I can test a Windows install later today but it might be gulp that doesn't work right on Windows... So I may be wrong with Windows, but I've never even tried. I can't remember what part of our workflow isn't supported.

**Comment by bebaps** [comment]
Okay, that makes sense. I never had that perspective since you added that functionality and there never was really an explanation why. So is that going to be a hinderance if Prelude is ever distributed via a different package manager... ie why limit it to just NPM

**Comment by erwstout** [comment]
Right now the copying of the files to the root is only via `npm` install, as it's part of the `postinstall` script inside of `package.json`. Right now we are only delivering via `npm`. The reason for this is that the view universally of package managers is sort of like `npm` is more of your core, backend (stuff the user doesnt see, IE prelude, gulp, etc) and that bower is more of a frontend what the user sees kind of thing (Slick Slider, Nifty Nav, etc).. Thats not to say that some backend packages might be available on bower, but thats generally how we've worked  out our projects.

We can't really stop a user from installing incorrectly, and if they dont install via npm then its on them really or they are smart enough to do what they need to do. I think for the purposes of us here at Factor1 all of our projects should have its own `package.json` with Prelude as a dependency. That way if I clone a repo that Matt or Alexander works on I can run `npm install && bower install` and get all of the node/bower packages I need to get up and running with a dev environment.
