### ISSUE TITLE
Install Fails on Windows via GitBash

### ISSUE THREAD

**Issue by erwstout** [factor1/prelude-wp#69]
So this is tricky and I almost want to just put this off for a bit for a few reasons. IF prelude is already installed in a repo/project you can run it just fine (but the chances of this are small, it worked for me because I was working out of a project folder that was setup on Linux.) 

Installing Prelude via GitBash on Win10 does fail, simply because of the `postinstall` script that @bebaps and I talked about in #68 

I'm almost hesitant to even put time into this since any day now Microsoft should be releasing a full Ubuntu Bash tool which _should_ eliminate the issue and since we don't usually develop on Windows machines at the moment, anyhow. 

Another thought is that we could remove the `postinstall` script by default and add an additional step such as `prelude-copy` to be ran from the CLI that will fire a node script to copy the files.

I'm leaning towards just waiting this out until the Windows 10 update and officially supporting it after that. Anyone who is working with open source / CLI tools on Windows are already used to things like this (I would assume) and are also looking forward to the Windows 10 Ubuntu release. 

Additionally we could have a Windows fork that does not include the `postinstall` script. 

Any thoughts?

**Comment by erwstout** [comment]
Will fork Prelude after `release/3.3.0` is pushed for a Windows version.... for now.

**Comment by erwstout** [comment]
So i forked prelude for a windows version, and it works. But then actually trying to apply that forked version to a project that is already up and going kinda creates some problems. Ive been doing some more thinking about how we automatically move the files to the root of the project, and while I think this is 100% useful and needed, I'm now leaning to the fact that our package probably shouldn't automatically be moving user files without permission. 

SO.

Speak now or forever hold your peace my proposed fix that would resolve the install issue on Windows AND be better for a new release:

User installs prelude:
`$  npm install prelude-wp --save`

User copies files:
`$ name-of-script-or-command-i-will-create-to-move-files`

and BOOM we are good. Windows users would need to manually move all files in `/src/` to their project.

We good? :-) @mattada @bebaps

**Comment by bebaps** [comment]
This kinda brings me back to my original train of thought. I don't see the benefit of doing this. Is it helpful, yes, but is it something that is absolutely critical and necessary for Prelude to work, I don't think so. In my opinion, we should have one of two ways Prelude works: either restructure the project so that everything is in the root to begin with and it works as is out of the box, or we leave the structure the way that it is and just make sure that we have a Gulp task to handle moving the files to a new directory where development can take place.

Again, we cant really rely on folks to fully read the instructions to set up Prelude properly. I think this is adding functionality "just because", and not because it is a vital part of Prelude itself. 

So I think making this functionality optional is good, but we just need to ensure that the project also works  without it.

**Comment by erwstout** [comment]
Well it wouldn't be a gulp task because the gulp file wouldn't be in the users directory, which is why it would be a node script. I think the key here is making it more universally compatible so I believe the answer is to leave the setup as is, but remove the `postinstall` script and create a node script instead.

**Comment by erwstout** [comment]
Pasting for later use:

```js
var source = fs.createReadStream('/path/to/source');
var dest = fs.createWriteStream('/path/to/dest');

source.pipe(dest);
source.on('end', function() { /* copied */ });
source.on('error', function(err) { /* error */ });
```

**Comment by erwstout** [comment]
Closing... Prelude should work since we removed the copying of files.
