### ISSUE TITLE
Add p:empty

### ISSUE THREAD

**Issue by bebaps** [factor1/prelude-wp#74]
Just a thought, we should include
```
p:empty {
    display: none !important;
  }
```
in the global scope to catch all those empty `<p>` tags WordPress loves into include if someone is using the WYSIWYG editor. I know WordPress does this and uses them as spacers, but it just causes unexpected results.

**Comment by erwstout** [comment]
Yeah, I'm on board. I just did some testing on it and it will still allow users to enter multiple breaks in their content which I think is a plus, since WordPress adds `&nbsp;` into the `<p>` because its not actually empty.

This can help though when in some cases ACF fields produce empty `<p>` (although we should be avoiding that).

But, if you're goal was to remove the `<p>&nbsp;</p>` this method would not work.

Any thoughts @mattada ?

**Comment by bebaps** [comment]
No, I am avoiding `<p></p>`

**Comment by mattada** [comment]
To erics point, i think WordPress still pushes the &nbsp; doesnt it?

Otherwise its a good idea to roll out.


Matt Adams
mattadams@factor1studios.com  |  twitter.com/mattada


*factor1*
factor1studios.com  |  twitter.com/factor1
602.334.4806 office  |  602.509.7553 mobile

On Thu, Aug 18, 2016 at 12:29 PM, Alexander Persky <notifications@github.com

**Comment by erwstout** [comment]
Pushed live with release `3.3.3`
