### ISSUE TITLE
Discussion: Add thumbnail max sizes as a default in /inc/thumbnails.php

### ISSUE THREAD

**Issue by mattada** [factor1/prelude-wp#95]
We all know clients will someday upload some giant photo that is a hog on download speeds. 

Thoughts on including one size for a max crop at 2000px wide?

**Comment by erwstout** [comment]
My only thought would be that a theme shouldn't be pulling in an image without a crop size anyway, so this in theory shouldn't be in issue? 

For instance, with heros, you should have a thumbnail size defined for the hero, or any other place in your theme you're pulling in an image. 

In the WP wysiwyg, it also doesn't default to full size. I know this used to be more of an issue in the past, but thats because we weren't setting thumbnail sizes for ACF fields.

**Comment by bebaps** [comment]
I think 2000-2500px is a good base for a default thumbnail size. And in Prelude these will need to be updated, as these are pulling the full image size by default:

```// Get featured image as URL
function featuredURL( $size = 'full' ) {
  $thumb = wp_get_attachment_image_src( get_post_thumbnail_id( $post->ID ), $size );
  $url   = $thumb['0'];

  echo $url;
}

// Get featured image as URL and output style property
function featuredBG( $size = 'full', $pos_x = 'center', $pos_y = 'center', $repeat = 'no-repeat' ) {
  $thumb = wp_get_attachment_image_src( get_post_thumbnail_id( $post->ID ), $size );
  $url   = $thumb['0'];

  echo 'style="background: url(' . $url . ')' . $pos_x . ' ' . $pos_y . ' ' . $repeat . '"';
}
```

**Comment by erwstout** [comment]
My first question still stands though, as a theme developer, you shouldn't be pulling in full size in any function or part of the theme, correct?

**Comment by bebaps** [comment]
To me that depends on context. For us, it wouldn't matter since we wouldn't upload an image that large anyway to our site, so pulling full size images would never be an issue to begin with.

This context is because we don't trust clients to follow that same reasoning, and they will upload whatever. An argument can be made that a min size could even be 5000px or more to account for retina displays, TVs, projectors, etc where a much larger resolution is needed for the image to still be crisp on whatever display is needed (not assuming that the default WP responsive images is properly serving adequate file sizes).

So I am in favor of a base thumbnail size, and changing these functions to reflect that base.

**Comment by erwstout** [comment]
I guess my point is that if we are following best practices when building our sites, full images would never be shown.

Bad Practice:
```php
// in a post loop
the_post_thumbnail();
```

Expected Practice:
```php
// in a post loop
the_post_thumbnail('news_thumb');
```

It shouldn't matter _what_ size the client/user uploads because anywhere we are using `the_post_thumbnail()` or ACF Images, we are defining what thumbnail it should be. 

Even when I user in a WYSIWYG enters an image via the Media Uploader, it doesn't show full width, it defaults to large (and a user can select a thumbnail size to choose from).

So my overall question is, where is this an issue? I _get_ what the point of doing it is, but where the disconnect for me is _when_ would a full size source image be shown (other than the custom functions, which just like `the_post_thumbnail` should have an argument for what thumbnail size to use.)

Am I making sense/misunderstanding?

**Comment by mattada** [comment]
So I guess I'm thinking the correct approach here will need to be as responsible developers we just never pull a full size thumbnail. 

If we dont know a size spec, ask the designer or think on your feet and guess. I can say 99% of the time 2000px or so is probably the right answer.

**Comment by bebaps** [comment]
I get what you are saying, but I do not agree with your example. If that was a bad practice, `the_post_thumbnail()` would not be the default use of this function. And you are right, custom functions should have an argument for what thumbnail size to use, and the one in Prelude currently is defaulting to the full size image. 

The 2000px suggestion is a safeguard (paired with updating the function).

An example of when a full size could be shown could be the original thought Susan had on the Tonik splash page, she wanted to have the slider images maintain aspect ratio regardless of the screen size the site was viewed on. Something like that will require some big ass images being used for that to happen on a 27 iMac. But I know that would suck so I just made the choice to limit the image sizes to like 1400px.

**Comment by erwstout** [comment]
So limiting the images in your Tonik example was the right call, and what I would consider to be a best practice to ensure the site is as fast and lean as possible. 

Yes, WordPress by default shows full image size when using `the_post_thumbnail()` but as a theme builder I believe it to be a bad practice to use that without passing a thumbnail size, for that "safe guarding" against massive images. 

I don't see the custom functions being any different than `the_post_thumbnail`. Yes the default is full size image, but it should always be a best practice to declare thumbnail sizes and pass them there, and that's what we would expect everyone on the team to do.
